# The server name set in Velocity that is used for logging in
loginServer: "login"
# The server name set in Velocity that the player will be transferred to after logging in
hubServer: "hub"
# The password players must input to log in
serverPassword: "1234"
# Change to false to make players have to write the password on every connection
oneTimeLogin: true

# Bypass settings require oneTimeLogin to be true

# group or user. Changes the method the plugins uses to check if a player must log in on every connection
# if set to user, players must be given the permission node defined in bypassNode.
# if set to group, players must be added to the group and the group must be created.
bypassMethod: "group"
# the group to check the player has if bypassMethod is set to group
bypassGroup: "loginbypass"
# the permission node to check if a player has set if bypassMethod is set to user
bypassNode: "loginpassword.bypass"
# if set to true, the plugin will set either the bypassGroup or the bypassNode when a user logins in
pluginGrantsBypass: true
# Set to false to allow the login command to be used by players with bypass permission
disableLoginCommandOnBypass: true

# Message to be sent to player if they fail to provide password after kickTimeout. Put "default" to have message read:
# You were kicked for failing to provide the password after kickTimeout seconds
kickMessage: "default"
# The amount of time to wait before kicking the player. In seconds
kickTimeout: 30
# Messages to be sent to player when they do not provide or gives a wrong password
noPassword: "Please provide a password. It can be found on Discord"
wrongPassword: "Wrong Password."

# set to false to make the login command only accessible to players with the permission node loginauth.login.
# this could be used to have a private server where only some players have access to. oneTimeLogin must be disabled otherwise players with the bypass permissions will always be sent to the private server.
loginCommandNegated: "true"

