name: loginPassword
version: ${version}
main: net.trim02.loginPassword.loginPasswordPaper
bootstrapper: net.trim02.loginPassword.paper.loginPasswordBootstrap
api-version: '${apiVersion}'
author: trim02
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true
    ViaVersion:
      load: BEFORE
      required: false
      join-classpath: true
