name: loginPassword
version: ${version}
main: net.trim02.loginPassword.loginPasswordPaper
api-version: '${apiVersion}'
author: trim02
soft-depend:
  - LuckPerms
  - ViaVersion
commands:
    loginpassword:
        description: Main command for loginPassword plugin
        usage: /loginpassword <subcommand>
        permission: loginpassword.admin